name: build
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup dotnet
        uses: actions/setup-dotnet@v3

      - name: dotnet restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build -c release

      - name: publish artifacts
        uses: actions/upload-artifact@v4
        with:
          path: src\TotalTimeloss\bin\Release\net481\LiveSplit.TotalTimeloss.dll
